//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthInfo
    {
        public string OAuthConsumerKeyString { get; set; }
        public string OAuthConsumerSecretString { get; set; }
        public Nullable<int> GetTwettNumber { get; set; }
        public string AccessToken { get; set; }
        public string TokenSecret { get; set; }
        public int id { get; set; }
    }
}
