//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TweetPost
    {
        public int id { get; set; }
        public string tweet { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string type { get; set; }
    }
}
