//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TweetPost
    {
        public int id { get; set; }
        public string tweet { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
